name: Check style

on:
  # Check style after every push to main
  push:
    branches:
      - main
  # Check style on every PR
  pull_request:

jobs:

  style:
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT_FILE: environment.yml
      ENVIRONMENT_NAME: simpeg-user-tutorials

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Miniforge
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: ${{ env.ENVIRONMENT_FILE }}
          activate-environment: ${{ env.ENVIRONMENT_NAME }}

      - name: Check style of notebooks
        run: make check
