name: Rerun the notebooks

on:
  pull_request:
  push:
    branches:
      - main
  # Run this action manually (this file needs to be in the default branch)
  workflow_dispatch:

jobs:
  run-notebooks:
    runs-on: ubuntu-latest
    env:
      PYTHON: "3.10"

    # Use bash by default in all jobs
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ env.PYTHON }}
          activate-environment: simpeg-user-tutorial
          environment-file: environment.yml
          auto-activate-base: false

      - name: List installed packages
        run: |
          conda info
          conda list

      - name: Run notebook
        run: |
          for notebook in notebooks/**/*.ipynb; do
            echo "Running '$notebook'"
            jupyter execute --inplace $notebook
          done
